### ISSUE TITLE
Feat(UI): Standardise Notes, board, rows using MUI

### ISSUE THREAD

**Issue by narainkarthikv** [narainkarthikv/sticky-memo#66]
Implement styling and responsive views using MUI standards and organize styles effectively.

## **Tasks**
- [x] Ensure all component styling uses **CSS-IN-JS** (Material-UI's `makeStyles` or `styled` API).  
- [x] Place all styles in the `styles` directory and import them into their respective components for modularity.
- [x] Ensure responsiveness across devices using MUI's **breakpoints** API.
